In [1]:
import torch
import numpy as np

In [2]:
# Define a tensor with default values
x = torch.ones(2,2)
print(x)
print(x.dtype)

# Define a tensor with specific data types
x =  torch.ones(2,2, dtype = torch.int8)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [5]:
# Changing a tensor's data type
x = torch.ones(1, dtype = torch.uint8)
print(x.dtype)

x= x.type(torch.float)
print(x.dtype)

torch.uint8
torch.float32


In [8]:
# Converting tensors into numpy arrays
x = torch.rand(2,2)
print(x)
print(x.dtype)

y = x.numpy()
print(y)
print(y.dtype)

tensor([[0.7907, 0.3502],
        [0.8019, 0.4064]])
torch.float32
[[0.79068    0.350164  ]
 [0.80193454 0.4064194 ]]
float32


In [11]:
# Converting Numpy arrays into tensors
# define a numpy array
x = np.zeros((2,2), dtype = np.float32)
print(x)
print(x.dtype)

# convert a numpy array to pytorch tensor
y = torch.from_numpy(x)
print(y)
print(y.dtype)

[[0. 0.]
 [0. 0.]]
float32
tensor([[0., 0.],
        [0., 0.]])
torch.float32


In [16]:
# Moving Tensors Between Devices
# define a cuda/gpu device
x = torch.tensor([1.5,2])
print(x)
print(x.device)

# Defune a cuda device
if torch.cuda.is_available():
    device = torch.device("cuda:0")

# Move tensor onto cuda
x = x.to(device)
print(x)
print(x.device)

# define a cpu device
device = torch.device("cpu")
x = x.to(device)
print(x)
print(x.device)

# define a tensor on device
device = torch.device("cuda:0")
x = torch.ones(2,2, device = device)
print(x)

tensor([1.5000, 2.0000])
cpu
tensor([1.5000, 2.0000], device='cuda:0')
cuda:0
tensor([1.5000, 2.0000])
cpu
tensor([[1., 1.],
        [1., 1.]], device='cuda:0')
